apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-calculadora
  namespace: laboratorio
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: backend-calculadora
  template:
    metadata:
      labels:
        app: backend-calculadora
    spec:
      containers:
        - name: backend
          image: 786137437644.dkr.ecr.us-east-1.amazonaws.com/backend-calculadora:1.0.1
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret