apiVersion: v1
kind: Service
metadata:
  name: backend-calculadora
  namespace: laboratorio
spec:
  type: LoadBalancer
  selector:
    app: backend-calculadora
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080