apiVersion: v1
kind: Service
metadata:
  name: frontend-calculadora
  namespace: laboratorio
spec:
  type: LoadBalancer
  selector:
    app: frontend-calculadora
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
